/**
 * sub-1caba-tile-redraw.test.ts — bit-perfect parity test of `sub1CABATileRedraw`
 * (replica of `FUN_0001CABA`) vs MAME ground truth.
 *
 * MAME captures `FUN_1CABA` is called 66 times during boot/level-init phase
 * (window f173..f257). The first call is the only NON-TRIVIAL case where
 * `struct_pre` != `struct_post`:
 *   - input: tileX=0x11, tileY=0x11, lvlPtr=0x2bee2, bsearchPtr=0x81874,
 *     workRam (incl. colBase + bsearchAlt populated by the caller right
 *     before the call), playfieldRam.
 *   - output: STRUCT @ 0x401C28..0x401C47 = `4000 * 16`.
 *
 * This test:
 *   1. Loads the captured MAME fixture (workRam + playfieldRam at fc=170 +
 *      first call entry state).
 *   2. Sets up the GameState with the captured fixture data.
 *   3. Runs `sub1CABATileRedraw`.
 *   4. Asserts the resulting STRUCT byte-for-byte against the MAME ground
 *      truth `struct_post`.
 *
 * Fixture was generated by:
 *   rm -f /tmp/mame_1caba_capture.json && \
 *   MARBLE_MAX=70 MARBLE_STOP=260 MARBLE_SNAP=172 \
 *   mame marble -window -nothrottle -skip_gameinfo -seconds_to_run 30 \
 *     -rompath roms -autoboot_script oracle/mame_1caba_capture.lua \
 *     -autoboot_delay 0
 *
 * Full 54/54 parity (= every captured call) is verified by the CLI script
 * `packages/cli/src/test-sub-1caba-parity.ts`.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { sub1CABATileRedraw } from "../src/sub-1caba-tile-redraw.js";
import { spritePosUpdate1BAB2 } from "../src/sprite-pos-update-1bab2.js";
import { bootInit } from "../src/boot-init.js";
import { emptyGameState } from "../src/state.js";
import { emptyRomImage } from "../src/bus.js";
import { loadRomBlob } from "../src/m68k/apply-slapstic-bank.js";

const FIXTURE_PATH = resolve(__dirname, "fixtures", "sub-1caba-firstcall.json");
const ROM_PATH = resolve(__dirname, "..", "..", "..", "ghidra_project", "marble_program.bin");
const L2_SEED_PATH = resolve(
  __dirname,
  "..",
  "..",
  "web",
  "public",
  "scenarios",
  "playable",
  "start_level2_intro_beginner_f2436.seed.json",
);

interface CallTrace {
  frame: number;
  tileX: string;
  tileY: string;
  lvlPtr: string;
  bsearchPtr: string;
  struct_pre: string;
  struct_post: string;
  colBase: string;
  bsearchAlt: string;
}

interface Fixture {
  workRam: string;
  playfieldRam: string;
  spriteRam: string;
  firstCall: CallTrace;
}

interface PlayableSeed {
  slapsticBank?: number;
  workRam: string;
  playfieldRam: string;
  spriteRam: string;
  alphaRam: string;
  colorRam: string;
}

function hex2bytes(hex: string, len: number): Uint8Array {
  const out = new Uint8Array(len);
  for (let i = 0; i < len && i * 2 + 1 < hex.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function writeWordBE(ram: Uint8Array, off: number, v: number): void {
  ram[off] = (v >>> 8) & 0xff;
  ram[off + 1] = v & 0xff;
}
function writeLongBE(ram: Uint8Array, off: number, v: number): void {
  ram[off] = (v >>> 24) & 0xff;
  ram[off + 1] = (v >>> 16) & 0xff;
  ram[off + 2] = (v >>> 8) & 0xff;
  ram[off + 3] = v & 0xff;
}

describe("sub1CABATileRedraw (FUN_0001CABA) — bit-perfect parity vs MAME", () => {
  it("first call @ f173: produces 4000*16 from struct_pre=0", () => {
    const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as Fixture;

    const rom = emptyRomImage();
    rom.program.set(readFileSync(ROM_PATH).subarray(0, rom.program.length));

    const state = emptyGameState();
    state.workRam.set(hex2bytes(fixture.workRam, 0x2000));
    state.playfieldRam.set(hex2bytes(fixture.playfieldRam, 0x2000));
    state.spriteRam.set(hex2bytes(fixture.spriteRam, 0x1000));

    const c = fixture.firstCall;

    // Override globals with per-call entry values (caller populates these
    // just before the call; snapshot @ fc=172 has them stale).
    writeWordBE(state.workRam, 0x696, parseInt(c.tileX, 16) & 0xffff);
    writeWordBE(state.workRam, 0x698, parseInt(c.tileY, 16) & 0xffff);
    writeLongBE(state.workRam, 0x474, parseInt(c.lvlPtr, 16) >>> 0);
    writeLongBE(state.workRam, 0x65a, parseInt(c.bsearchPtr, 16) >>> 0);

    // struct_pre into workRam[0x1c28..0x1c47] (= input to sub)
    state.workRam.set(hex2bytes(c.struct_pre, 32), 0x1c28);

    // Per-call workRam regions captured at the moment of the call entry.
    // Critical: colBase @ 0x478..0x677 and bsearchAlt @ 0x76E..0x96D are
    // populated by the caller of FUN_1CABA right before the call. The
    // global snapshot at fc=172 has them zeroed-out (= stale).
    state.workRam.set(hex2bytes(c.colBase, 0x200), 0x478);
    state.workRam.set(hex2bytes(c.bsearchAlt, 0x200), 0x76e);

    // Run the replica
    sub1CABATileRedraw(state, rom);

    // Extract post-state STRUCT
    const tsStructBytes = state.workRam.subarray(0x1c28, 0x1c28 + 32);
    const tsStructHex = Array.from(tsStructBytes)
      .map(b => b.toString(16).padStart(2, "0"))
      .join("");

    expect(tsStructHex).toBe(c.struct_post);
  });

  it("tc=0 path clears 8 bytes via 2x clr.l (A5)+ per disasm", () => {
    // Verifies disasm-correct behavior at 0x1cb72 (beq.w +0xce → 0x1cc42 =
    // `clr.l (A5)+; clr.l (A5)+`). When all 4 iters take tc=0 path, sub1CABA
    // writes 32 zero bytes to STRUCT @ 0x1c28..0x1c47.
    //
    // Setup: all-zero workRam (= bsearchAlt all 0) + zero playfield → every
    // dispatch reads terrainCode=0 → PATH_TC_ZERO → write 0s via clr.l.
    // The 4 iters write to interleaved offsets (per ROM table @ 0x24b3a)
    // covering all 16 word slots.
    const rom = emptyRomImage();
    rom.program.set(readFileSync(ROM_PATH).subarray(0, rom.program.length));

    const state = emptyGameState();
    // Set struct_pre = 4000*16 to verify it gets cleared.
    for (let i = 0; i < 16; i++) {
      writeWordBE(state.workRam, 0x1c28 + i * 2, 0x4000);
    }
    // Ensure d2Max is large enough to avoid abortBody trigger (set lvlPtr+0x18 to a high value).
    // Default zero state means lvlPtr=0 → readWord(0x18) = 0 → d2Max=0 → abortBody triggers
    // (which ALSO writes zeros via the same clr.l clr.l mechanism).
    sub1CABATileRedraw(state, rom);
    // All 16 word slots should be cleared to 0 (either via tc=0 or abortBody;
    // both paths write 8 zeros per iter via clr.l (A5)+ at 0x1cc42).
    for (let i = 0; i < 16; i++) {
      const w = (state.workRam[0x1c28 + i * 2]! << 8) | state.workRam[0x1c28 + i * 2 + 1]!;
      expect(w).toBe(0);
    }
  });

  it("Beginner L2 tile (78,67) reads the video RAM row that lands in motion-object RAM", () => {
    const seed = JSON.parse(readFileSync(L2_SEED_PATH, "utf-8")) as PlayableSeed;

    const rom = emptyRomImage();
    loadRomBlob(rom, readFileSync(ROM_PATH));

    const state = emptyGameState();
    bootInit(state, rom, {
      warmState: {
        workRam: hex2bytes(seed.workRam, 0x2000),
        playfieldRam: hex2bytes(seed.playfieldRam, 0x2000),
        spriteRam: hex2bytes(seed.spriteRam, 0x1000),
        alphaRam: hex2bytes(seed.alphaRam, 0x1000),
        colorRam: hex2bytes(seed.colorRam, 0x800),
        slapsticBank: seed.slapsticBank ?? 1,
      },
    });

    const playerOff = 0x18;
    writeLongBE(state.workRam, playerOff + 0x0c, Math.round(628 * 0x10000) >>> 0);
    writeLongBE(state.workRam, playerOff + 0x10, Math.round(536.9 * 0x10000) >>> 0);
    writeLongBE(state.workRam, playerOff + 0x14, Math.round(16176 * 0x10000) >>> 0);
    writeWordBE(state.workRam, 0x696, 0xffff);
    writeWordBE(state.workRam, 0x698, 0xffff);

    spritePosUpdate1BAB2(state, 0x00400018, {
      fun_1CABA: (s) => { sub1CABATileRedraw(s, rom); },
    });

    expect(((state.workRam[0x696] ?? 0) << 8) | (state.workRam[0x697] ?? 0)).toBe(78);
    expect(((state.workRam[0x698] ?? 0) << 8) | (state.workRam[0x699] ?? 0)).toBe(67);
    expect(((state.workRam[0x1c36] ?? 0) << 8) | (state.workRam[0x1c37] ?? 0)).toBe(0x3f30);
  });
});
