/**
 * sub-1caba-tile-redraw.test.ts — bit-perfect parity test of `sub1CABATileRedraw`
 * (replica of `FUN_0001CABA`) vs MAME ground truth.
 *
 * MAME captures `FUN_1CABA` is called 66 times during boot/level-init phase
 * (window f173..f257). The first call is the only NON-TRIVIAL case where
 * `struct_pre` != `struct_post`:
 *   - input: tileX=0x11, tileY=0x11, lvlPtr=0x2bee2, bsearchPtr=0x81874,
 *     workRam (incl. colBase + bsearchAlt populated by the caller right
 *     before the call), playfieldRam.
 *   - output: STRUCT @ 0x401C28..0x401C47 = `4000 * 16`.
 *
 * This test:
 *   1. Loads the captured MAME fixture (workRam + playfieldRam at fc=170 +
 *      first call entry state).
 *   2. Sets up the GameState with the captured fixture data.
 *   3. Runs `sub1CABATileRedraw`.
 *   4. Asserts the resulting STRUCT byte-for-byte against the MAME ground
 *      truth `struct_post`.
 *
 * Fixture was generated by:
 *   rm -f /tmp/mame_1caba_capture.json && \
 *   MARBLE_MAX=70 MARBLE_STOP=260 MARBLE_SNAP=172 \
 *   mame marble -window -nothrottle -skip_gameinfo -seconds_to_run 30 \
 *     -rompath roms -autoboot_script oracle/mame_1caba_capture.lua \
 *     -autoboot_delay 0
 *
 * Full 54/54 parity (= every captured call) is verified by the CLI script
 * `packages/cli/src/test-sub-1caba-parity.ts`.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { sub1CABATileRedraw } from "../src/sub-1caba-tile-redraw.js";
import { emptyGameState } from "../src/state.js";
import { emptyRomImage } from "../src/bus.js";

const FIXTURE_PATH = resolve(__dirname, "fixtures", "sub-1caba-firstcall.json");
const ROM_PATH = resolve(__dirname, "..", "..", "..", "ghidra_project", "marble_program.bin");

interface CallTrace {
  frame: number;
  tileX: string;
  tileY: string;
  lvlPtr: string;
  bsearchPtr: string;
  struct_pre: string;
  struct_post: string;
  colBase: string;
  bsearchAlt: string;
}

interface Fixture {
  workRam: string;
  playfieldRam: string;
  spriteRam: string;
  firstCall: CallTrace;
}

function hex2bytes(hex: string, len: number): Uint8Array {
  const out = new Uint8Array(len);
  for (let i = 0; i < len && i * 2 + 1 < hex.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function writeWordBE(ram: Uint8Array, off: number, v: number): void {
  ram[off] = (v >>> 8) & 0xff;
  ram[off + 1] = v & 0xff;
}
function writeLongBE(ram: Uint8Array, off: number, v: number): void {
  ram[off] = (v >>> 24) & 0xff;
  ram[off + 1] = (v >>> 16) & 0xff;
  ram[off + 2] = (v >>> 8) & 0xff;
  ram[off + 3] = v & 0xff;
}

describe("sub1CABATileRedraw (FUN_0001CABA) — bit-perfect parity vs MAME", () => {
  it("first call @ f173: produces 4000*16 from struct_pre=0", () => {
    const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as Fixture;

    const rom = emptyRomImage();
    rom.program.set(readFileSync(ROM_PATH).subarray(0, rom.program.length));

    const state = emptyGameState();
    state.workRam.set(hex2bytes(fixture.workRam, 0x2000));
    state.playfieldRam.set(hex2bytes(fixture.playfieldRam, 0x2000));
    state.spriteRam.set(hex2bytes(fixture.spriteRam, 0x1000));

    const c = fixture.firstCall;

    // Override globals with per-call entry values (caller populates these
    // just before the call; snapshot @ fc=172 has them stale).
    writeWordBE(state.workRam, 0x696, parseInt(c.tileX, 16) & 0xffff);
    writeWordBE(state.workRam, 0x698, parseInt(c.tileY, 16) & 0xffff);
    writeLongBE(state.workRam, 0x474, parseInt(c.lvlPtr, 16) >>> 0);
    writeLongBE(state.workRam, 0x65a, parseInt(c.bsearchPtr, 16) >>> 0);

    // struct_pre into workRam[0x1c28..0x1c47] (= input to sub)
    state.workRam.set(hex2bytes(c.struct_pre, 32), 0x1c28);

    // Per-call workRam regions captured at the moment of the call entry.
    // Critical: colBase @ 0x478..0x677 and bsearchAlt @ 0x76E..0x96D are
    // populated by the caller of FUN_1CABA right before the call. The
    // global snapshot at fc=172 has them zeroed-out (= stale).
    state.workRam.set(hex2bytes(c.colBase, 0x200), 0x478);
    state.workRam.set(hex2bytes(c.bsearchAlt, 0x200), 0x76e);

    // Run the replica
    sub1CABATileRedraw(state, rom);

    // Extract post-state STRUCT
    const tsStructBytes = state.workRam.subarray(0x1c28, 0x1c28 + 32);
    const tsStructHex = Array.from(tsStructBytes)
      .map(b => b.toString(16).padStart(2, "0"))
      .join("");

    expect(tsStructHex).toBe(c.struct_post);
  });

  it("no-op call: struct_pre=4000*16 → struct_post=4000*16 (preservation)", () => {
    // Subsequent calls (frame > 173) typically have struct_pre == struct_post
    // because terrainCode read from bsearchAlt is zero in those iterations.
    // Verify the replica doesn't corrupt the struct when no terrain dispatch
    // triggers a write.
    const rom = emptyRomImage();
    rom.program.set(readFileSync(ROM_PATH).subarray(0, rom.program.length));

    const state = emptyGameState();
    // Default state: all zero workRam + playfield. Set struct_pre = 4000*16.
    for (let i = 0; i < 16; i++) {
      writeWordBE(state.workRam, 0x1c28 + i * 2, 0x4000);
    }
    // tileX/tileY = 0 (default). lvlPtr = 0 (no level data). With all-zero
    // workRam, all terrainCode reads return 0 → no writes occur.
    sub1CABATileRedraw(state, rom);
    for (let i = 0; i < 16; i++) {
      const w = (state.workRam[0x1c28 + i * 2]! << 8) | state.workRam[0x1c28 + i * 2 + 1]!;
      expect(w).toBe(0x4000);
    }
  });
});
